config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get 'searchs/search' => 'searchs#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key:  "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  
    def after_sign_in_path_for(resource)
      user_path(current_user.id)
    end
    
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.user_id = current_user.id
    @book_comment.save
    render :book_comments
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
    render :book_comments
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully!"
    else
      @book = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully!"
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        User.where(title: content)
      elsif method == 'forward'
        User.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('title LIKE ?', '%'+content)
      elsif method == 'partial'
        User.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully"
    else
      render :edit
    end
    

    
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.html.erb
  <table>
    <% book.book_comments.each do |book_comment| %>
      <tbody>
        <tr>
          <td>
            <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "30x30" %><br>
            <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
          </td>
          <td><%= book_comment.comment %></td>
          <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %></td>
        </tr>
      </tbody>
    <% end %>
  </table>

app/views/book_comments/_new_comment.html.erb
<%= form_with model:[book, book_comment], remote: true do |f| %>
  <%= f.text_area :comment, remote:true, rows: '5', placeholder: "コメントをここに", class: "form-control mt-3" %>
  <%= f.submit "送信する" %>
<% end %>

app/views/book_comments/book_comments.js.erb
$("#comments_area").html("<%= escape_javascript(render partial: 'book_comments/index', locals: { book: @book }); %>")

$("textarea").val('');

app/views/books/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-5 mt-3 mx-auto">
      <%= render "users/errors", user: @book %>
      <h2>Editing Book</h2>
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class: 'form-control', rows: '2' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update book", class: 'btn btn-success' %>
        </div>
      <% end %>
      
      <%= link_to "Show", book_path(@book.id) %>
      <span> | </span>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="containar">
  <div class="row">
    <div class="col-3">

      <%= render 'users/left-bar', user: current_user, book: @book %>

    </div>
    <div class="col-8 offset-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thread>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thread>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to (attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50"), user_path(book.user_id) %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td id="favorite-btn-<%= book.id %>">
              <%= render 'favorites/favorite-btn', book: book %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="containar">
  <div class="row">
    <div class="col-3">

      <%= render 'users/left-bar', user: @book.user, book: @new_book %>

    </div>

    <div class="col-8 offset-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td><%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
                <%= link_to @book.user.name, user_path(@book.user.id) %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= render 'favorites/favorite-btn', book: @book %></td>
            <td>コメント：<%= @book.book_comments.count %> 件</td>
            <% if @book.user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div id="comments_area">
        <%= render 'book_comments/index', book: @book %>
      </div>

      <div class="new-comment">
        <%= render 'book_comments/new_comment', book: @book, book_comment: @book_comment %>
      </div>
      
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart like-btn-unlike" do %>
      <%= book.favorites.count %> いいね
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart like-btn" do %>
      <%= book.favorites.count %> いいね
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$('#favorite-btn-<%= @book.id %>').html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorite-btn-<%= @book.id %>').html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row mx-auto">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>In <i class="fas fa-book"></i>Bookers,</p>
        <p>you can share and exchange your opinions, inpressions, and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block md-3" %>
          </div>

        </div>

      </div>
    </div>
</div>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followinds.html.erb
<h2>Followings Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searchs/_search_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: searchs_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
<% end %>

app/views/searchs/search.html.erb
<% if @model == 'user' %>
	<h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% elsif @model == 'book' %>
	<h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_errors.html.erb
<% if user.errors.any? %>
<h2 class="alert alert-danger" role="alert"><%= user.errors.count %>errors prohibited this obj from being saveed:</h2>
  <% user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/users/_index.html.erb
  <table class="table">
    <thread>
      <tr>
        <th>neme</th>
        <th>image</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thread>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/_left-bar.html.erb
<h2>User info</h2>
  <table class="table">
    <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
    <tbody>
      <tr>
        <td>name</td>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <td>introduction</td>
        <td><%= user.introduction %></td>
      </tr>
      <tr>
        <td>followers</td>
        <td><%= link_to user.followings.count, user_followings_path(user) %></td>
      </tr>
      <tr>
        <td>followings</td>
        <td><%= link_to user.followers.count, user_followers_path(user) %></td>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <div class="follow_btn">
      <% unless current_user == user %>
        <% if current_user.following?(user) %>
          <%= link_to "フォローを外す", user_relationship_path(user.id), method: :delete, class: "btn btn-info" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <%= link_to "", edit_user_path(user.id), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>

  <h2>New book</h2>
  <%= form_with model: book, local: true do |f| %>
    <label>Title</label>
    <%= f.text_field :title, class:"form-control" %>
    <label>Opinion</label>
    <%= f.text_area :body, class:"form-control", rows:"3" %>
    <%= f.submit "Create Book", class:"btn btn-info btn-lg btn-block mt-4"%>
  <% end %>

app/views/users/edit.html.erb
<div class="container mx-auto">
  <div class="row mx-auto">
    <div class="col-5 mx-auto">
      <%= render "users/errors", user: @user %>
      <h1>User info</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label>Image</label>
          <%= f.attachment_field :profile_image %>
        </div>
        <div>
          <label>Introduction</label>
          <%= f.text_area :introduction, class: 'form-control' %>
        </div>
        <div class="form-group mt-3">
          <%= f.submit "Update User", class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="containar">
  <div class="row">
    <div class="col-3">

      <%= render 'users/left-bar', user: @user, book: @book %>

    </div>
    <div class="col-8 offset-1">
      <h2>Users</h2>
      <table class="table table-hover table-in">
        <thread>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thread>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: 'no_image.jpg', size: "50x50" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="containar">
  <div class="row">
    <div class="col-3">

      <%= render 'users/left-bar', user: @user, book: @book %>

    </div>

    <div class="col-8 offset-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thread>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thread>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to (attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50"), user_path(book.user_id) %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>